### ISSUE TITLE
Update tutorials with change from neurodesktop-storage to storage

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurodesk.github.io#105]

**Comment by civier** [comment]
Hi Aswin. When you change to storage, can you please have in Neurodesk a symbolic link from neurodesktop-storage to storage, to maintain backwards compatibility?

**Comment by stebo85** [comment]
@civier - you misundertand the issue: This is about renaming the link on the desktop that already happened months ago because an issue was raised that the name is truncated. Now the tutorials need to be adjutsed because some might still refer to the old link on the desktop.

**Comment by civier** [comment]
Ooops. Sorry.
