### ISSUE TITLE
Unable to run any application

### ISSUE THREAD

**Issue by Edouard2laire** [NeuroDesk/neurodesk.github.io#107]
Hello, 
First, thanks a lot for creating this great tool;
I am contacting you since, since I acquired a new mac, I am not able to run any application from the NeuroDesk. I tried to reinstall both Docker and Neurodesk without any success. 

When launching an application, a consol will appear and then close without launching the software. This only concerns the application not already included in Neurodesk (Firefox, text editors.. works) but not SPM, brainstorm...

I tried to launch the following command: 

> user@neurodesktop-20220128:~$  /neurocommand/local/fetch_and_run.sh spm12 r7771 20211206
> [DEBUG] fetch_and_run.sh: Script name : /neurocommand/local/fetch_and_run.sh
> [DEBUG] fetch_and_run.sh: Current working dir : /home/user
> [DEBUG] fetch_and_run.sh: Script location path (dir) : /neurocommand/local
> [DEBUG] fetch_and_run.sh: SINGULARITY_BINDPATH : /afm01,/afm02,/cvmfs,/90days,/30days,/QRISdata,/RDS,/data,/short,/proc_temp,/TMPDIR,/nvme,/local,/gpfs1,/working,/winmounts,/state,/autofs,/cluster,/local_mount,/scratch,/clusterdata,/nvmescratch,/vnm,/neurodesktop-storage
> /neurocommand/local/config.ini
> CVMFS detected and Container seems to be available
> Mounting containers from CVMFS directly.
> 
> Due to MODULEPATH changes the following have been reloaded:
>   1) spm12/r7771
> 
> [DEBUG] fetch_and_run.sh: fetching containers done.
> [DEBUG] fetch_and_run.sh: MOD_NAME:  spm12
> [DEBUG] fetch_and_run.sh: MOD_VERS:  r7771
> [DEBUG] fetch_and_run.sh: Module 'spm12/r7771' is installed. Use the command 'module load spm12/r7771' outside of this shell to use it.
> [DEBUG] fetch_and_run.sh: looking for /cvmfs/neurodesk.ardc.edu.au/containers/spm12_r7771_20211206/spm12_r7771_20211206.simg
> [DEBUG] fetch_and_run.sh: Attempting to launch container spm12_r7771_20211206
> ERROR  : Failed to spawn stage 1
> ERROR  : Failed to spawn stage 1
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> the container /cvmfs/neurodesk.ardc.edu.au/containers/spm12_r7771_20211206/spm12_r7771_20211206.simg experienced an error.
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> [DEBUG] fetch_and_run.sh: module load spm12/r7771
> [DEBUG] fetch_and_run.sh: Running command ''.

and 

> user@neurodesktop-20220128:~$ module load spm12/r7771
> user@neurodesktop-20220128:~$ spm12
> ERROR  : Failed to spawn stage 1
> user@neurodesktop-20220128:~$ 

> user@neurodesktop-20220128:~$ cat `which spm12`       
> #!/usr/bin/env bash
> export PWD=`pwd -P`
> singularity exec  --pwd $PWD /cvmfs/neurodesk.ardc.edu.au/containers/spm12_r7771_20211206/spm12_r7771_20211206.simg spm12 "$@"

The main error seems to be this "Failled to spawn stage 1" but i have no idea to what that corresponds. 

Thanks a lot, 
Edouard

**Comment by aswinnarayanan** [comment]
Hi @Edouard2laire. Do you have the model for the new Mac?

**Comment by Edouard2laire** [comment]
It’s MacBook Pro 2020. Do you think that the fact that it is using an apple M1 chip might be the issue ?

**Comment by stebo85** [comment]
Dear @Edouard2laire - yes, most neuroimaging applications do not yet work on the M1 chip. We are aiming to get the ARM architecture supported but this is a multi-month effort where we need a lot of help from the community.

**Comment by stebo85** [comment]
Here is the issue where we would like to support M1: https://github.com/NeuroDesk/neurodesktop/issues/44 - but we are currently lacking the people power (and the money to purchase an M1) in the project to work on this. @Edouard2laire - are you keen to work on this?

**Comment by Edouard2laire** [comment]
yes, would be happy to help. Would you have any pointer on where to start?

**Comment by stebo85** [comment]
Dear @Edouard2laire,

great to hear you are keen to help :) The best point to get started is at the application container level: Since you would like to run SPM, but SPM requires Matlab, which is not yet supported on M1, I would start with trying to run SPM in Octave, which supports Arm. Could you try to build this container on your machine and see if SPM works? 

https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/niistat/build.sh

I am happy to schedule a zoom call in the next days to get you started on this. Get in touch via email: s.bollmann@uq.edu.au

Cheers
Steffen
