### ISSUE TITLE
enable google analytics for website?

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk.github.io#117]
This would give us some statistics on where interested users come from and what people are interested in?

https://gohugo.io/templates/internal/

**Comment by aswinnarayanan** [comment]
That's a good idea, I'll set one up now

**Comment by aswinnarayanan** [comment]
Working

**Comment by stebo85** [comment]
awesome :) That's fantastic! We will need to think more about how we can understand our users better without invading privacy - but this is a great start.
