### ISSUE TITLE
should we add a contributors page to highlight community contributors to the project?

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk.github.io#148]

**Comment by stebo85** [comment]
https://neurodesk.github.io/developers/contributors/

**Comment by aswinnarayanan** [comment]
Looking good. Should we move this to the documentation section. Probably weighted to the bottom

**Comment by stebo85** [comment]
Yes, that's a good idea, too - but waite for now on moving it, otherwise the link I sent in the email will be invalid :)

**Comment by air2310** [comment]
Looks great, thanks Steffen!
