### ISSUE TITLE
website 'secure connection failed'

### ISSUE THREAD

**Issue by meganEJcampbell** [NeuroDesk/neurodesk.github.io#162]
![screenshot](https://user-images.githubusercontent.com/34408937/160954944-1eb668ad-67fe-40fd-af7b-fb36f6c7df1e.png)

Firefox won't let me connect to www.neurodesk.org :-(

**Comment by aswinnarayanan** [comment]
Hi @meganEJcampbell, oh no thats not good.
I had a quick check online, is there any proxy settings enabled on your firefox? Or maybe a vpn running?
https://www.hostinger.com/tutorials/pr_end_of_file_error

**Comment by meganEJcampbell** [comment]
Thanks @aswinnarayanan for a quick reply! :D I tried accessing via Chrome and got the same thing but with a bit more detail so called uni IT and yep it was blocked! annoying!

**Comment by stebo85** [comment]
Oh, wow - did they unblock it @meganEJcampbell ? Did they say why it was blocked?

**Comment by meganEJcampbell** [comment]
IT unblocked it but gave no reason as to why it was blocked to begin with!

**Comment by stebo85** [comment]
ok, thank you for this information. We saw similar things at UQ and it was because the domain was too "new" - we let it age a bit before we switched over, but it seems it needs another round in the cellar for some university firewalls :D
