### ISSUE TITLE
Connection from VNC client doesn't work

### ISSUE THREAD

**Issue by korbinian90** [NeuroDesk/neurodesk.github.io#204]
docker run --shm-size=1gb -it --privileged --name neurodesktop -v C:/neurodesktop-storage:/neurodesktop-storage -p 5901:5901 -p 8080:8080 -h neurodesktop-20220813 vnmd/neurodesktop:20220813 --vnc

Connecting to port 5901 did not work (tested on windows with turbovnc 3.0.1)

**Comment by aswinnarayanan** [comment]
Hi @korbinian90. Can you test this build if this fixes the issue? (localhost::5901)
```
docker run --shm-size=1gb -it --privileged --name neurodesktop -v C:/neurodesktop-storage:/neurodesktop-storage -p 5901:5901 -p 8080:8080 -h neurodesktop-20220813 vnmd/neurodesktop:20221121 --vnc
```

**Comment by korbinian90** [comment]
Hi @aswinnarayanan. It does work now!
