### ISSUE TITLE
add copy button to code cells?

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk.github.io#25]
https://aaronluna.dev/blog/add-copy-button-to-code-blocks-hugo-chroma/

**Comment by aswinnarayanan** [comment]
@stebo85 Nice find!! I started trying to implement it and realised they've already added this via prism.js
https://www.docsy.dev/docs/adding-content/lookandfeel/#code-highlighting-with-prism
0e43e26d2e17058a4070d5267dde8c7b81984d51

**Comment by stebo85** [comment]
oh, that's soooo cool!!!
