### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk.github.io#254]
The neurodesk.org website search currently doesn't work.

It looks like we are using lunr to do this? Is this what we need to set it up?

https://codewithhugo.com/hugo-lunrjs-search-index/

@aswinnarayanan, was it never set-up or is just something simple broken?

Another option I found is using this search provider:
https://docsearch.algolia.com/

Any ideas what's causing the issue and how to best fix it :?

**Comment by aswinnarayanan** [comment]
I'll have a look

**Comment by aswinnarayanan** [comment]
Lets try algolia. I've applied for their docsearch, and it is already integrated into hugo docsy.

**Comment by aswinnarayanan** [comment]
Am fixing the Algolia search. I think I sent them the wrong domain (neurodesk.org instead of www.neurodesk.org)
Have asked them to update

**Comment by stebo85** [comment]
cool - that works actually quite well :)

**Comment by aswinnarayanan** [comment]
Updated to algolia search
