### ISSUE TITLE
Make it less confusing to communicate with us for people without Github accounts

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk.github.io#28]
Github's discussions is great for people to contact us, BUT ... if you're not registered to Github, you get this:
<img width="1680" alt="Screen Shot 2021-09-26 at 11 35 18 pm" src="https://user-images.githubusercontent.com/8280611/134810393-704a6d2a-2c6f-446a-9011-f9155aa147e2.png">

This is super stupid, because some people would not automatically figure out that they need to open an account on Github in order to post a new issue. It could have been much smarter if Github had included the "New Discussion" button anyway (popping up a message requesting to register), but they didn't. So as it stands right now -- things are rather confusing, and might deter some people.

As a simple solution, I suggest that under "Discussions" in our front page, we will write:
"Ask questions, suggest new features or raise any issues you have :)
 **(Github account required)**"
The part in bold is what I suggest to add.

I would have added it myself, but in the front page, I do not have the "Edit this page" option in the sidebar.

Cheers,
Oren

**Comment by stebo85** [comment]
Dear @civier,

I added it. The index page doesn't have an edit button, but can be changed here:
https://github.com/NeuroDesk/neurodesk.github.io/blob/hugo-docsy/content/en/_index.html


Kind regards
Steffen
