### ISSUE TITLE
incorrect installation instruction of neurodesk app for ubuntu

### ISSUE THREAD

**Issue by kel-github** [NeuroDesk/neurodesk.github.io#339]
Hey folks,

RE: this page - https://www.neurodesk.org/docs/getting-started/neurodesktop/neurodeskapp/ -

The instructions for installing the neurodesk app for Ubuntu read as: 
sudo apt install -f NeurodeskApp-Setup-Debian.deb

but I think it should be:
sudo apt install -f ./NeurodeskApp-Setup-Debian.deb

**Comment by kel-github** [comment]
I just made a pull request from my fork where I amended the instruction

**Comment by stebo85** [comment]
thank you :)
