### ISSUE TITLE
HPC - Installing (individual) containers

### ISSUE THREAD

**Issue by SaskiaBollmann** [NeuroDesk/neurodesk.github.io#404]
Dear neurodesk team,

I completely overlooked the description how to install individual containers on an HPC system:

<img width="489" alt="image" src="https://github.com/NeuroDesk/neurodesk.github.io/assets/25474977/e78bd1d8-18a3-4ae6-be6f-fbc4b075edc7">

It might be worthwhile to add one example on the documentation, as users may mainly look for the code snippets?

And I ran into some trouble, since I added a non-existing directory to the bindpath:

<img width="989" alt="image" src="https://github.com/NeuroDesk/neurodesk.github.io/assets/25474977/ccfd8160-b109-4117-8458-a6fca5485070">

Maybe it's worthwhile to note that non-existing paths need to be removed?

Thanks heaps,
Saskia

**Comment by stebo85** [comment]
ok, that's added now.
