### ISSUE TITLE
Docs: Manual build clarification

### ISSUE THREAD

**Issue by Lestropie** [NeuroDesk/neurodesk.github.io#452]
-----

From the [online documentation instructions for manual build](https://www.neurodesk.org/developers/new_tools/manual_build/):

> Create your Container Files:
> ...
> Upload your application to object storage first if needed, so you can then download it in build.sh (ask for instructions about this if you don’t know the key, and never share it anywhere public!)

That last line is to me cryptic. My best guess is that if a container has some data dependency, it is necessary for those data to be available publicly via a URL, such that they can be acquired via eg. `wget` or `curl` during the `neurodocker generate` command. However this private "object storage" is neither interpretable to an external user, nor would it seem to me to be a unique solution to this problem.

-----

> 3. Building containers
>   Any NEWAPP under the recipes/ directory are built and pushed automatically via github actions

> 4. Build and test the container locally

> 5. Update changes in local git repository

It would seem to me that not only is it good practise to build and test a container locally before pushing publicly, but also there is no way that a GitHub Action at point 3 could automatically build a new / modified container for which a commit has not yet been made, in which case these are out of order.

-----

**Comment by stebo85** [comment]
Dear @Lestropie,

Yes, agree - these build instructions are too complicated and we are currently working on making this easier. For now, I updated the text to explain things better.

Thank you for raising this issue! We are working on it.
