### ISSUE TITLE
any CVMFS mirrors

### ISSUE THREAD

**Issue by stdweird** [NeuroDesk/neurodesk.github.io#463]
If there are any cvmfs mirrors we can add to the configuration, please list them in the docs. If there are none, please describe the high availibility of the single server_url.

**Comment by stebo85** [comment]
Dear @stdweird - yes, we will document this in full details in the next days on our website! Thank you for raising it.

**Comment by stebo85** [comment]
Dear @stdweird ,

We now documented everything in detail: https://www.neurodesk.org/docs/getting-started/neurocontainers/cvmfs/

Can you have a look through and let us know if you need anything else?

**Comment by stdweird** [comment]
@stebo85 thanks for the list. i will use the list that you set in the variable `SERVER_URL`. 
one remark wrt the docs. i would move the description of the servers in a separate section, after the troubleshooting. this is pretty advanced, and changing that variable is probably only needed for setups running in eg aws. putting that whole description where it is now, forces people to read it, and i am quite sure it will confuse people ;)

**Comment by stebo85** [comment]
You don't need to add all servers - pick a few that are close to you only. Also depending on your setup you might want to use the direct servers and not the cdn aliases - especially when you are closer to one of the servers than what the cdn can provide you and if you are running a local proxy.

**Comment by stdweird** [comment]
@stebo85 ugh. you better document that as well ;)
i assumed that cvmfs would figure it out, eg based on the geoip data. i assume there is not cvmfs tool to give a list of urls, and the get it reordered with closest first? 

anyway, in our case, i'll use the nikhef one first, and then the aws frankfurt one (so i have 2 at least). any chance you can convince the aws maintainers to register a dns alias? the current hostname looks like it might change any time now ;)

thanks again

**Comment by stebo85** [comment]
Yes, the cvmfs client figures out where the servers are based on their ip address. That's what the USE_GEOAPI parameter controls.

It's also possible to probe the servers and measure the latency but the CDNs will always give a short response time which then doesn't translate to the real use case because it's rarely all in cache. I can add this to the documentation.

Yes, we can create another dns record for the Frankfurt server.

**Comment by stebo85** [comment]
Yes, i probably missed that

**Comment by stebo85** [comment]
I had a look at this again to complete this issue:

- update `s1nikhef-cvmfs.openhtc.io:8080 -> cvmfs01.nikhef.nl:8000` 
-  cvmfs-frankfurt.neurodesk.org is now a DNS entry to ec2-3-72-92-91.eu-central-1.compute.amazonaws.com

Let us know if you see anything else.

**Comment by stdweird** [comment]
@stebo85 hmm, why is the `:8000` needed for nikhef .nl? it seems to work on default port as well

**Comment by stebo85** [comment]
I don't think they are needed.
