### ISSUE TITLE
Easy access to the list of software available in Neurodesk

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk.github.io#53]
### Discussed in https://github.com/NeuroDesk/neurodesk.github.io/discussions/52

<div type='discussions-op-text'>

<sup>Originally posted by **civier** November 23, 2021</sup>
In the end, the most important factor that will draw people to try Neurodesk is if their favourite tool is already included in the platform. Right now, it requires like 3 clicks to reach to this information, and it is not so evident where one should look for that.
I suggest to have a link to the current software list already in the main page (https://neurodesk.github.io/), in the top toolbar ("Software"), or in the neurocontainers page (https://neurodesk.github.io/docs/neurocontainers/).

Also -- the list itself is not nicely formatted (https://github.com/NeuroDesk/neurocommand/blob/main/cvmfs/log.txt). It's not a big deal, but I think that search engines do not catch it. Right now, when I search in Google "Neurodesk EEGLAB" for example, it bring me here: https://github.com/NeuroDesk/neurocommand/blob/main/neurodesk/apps.json
which is a bit (a lot) difficult to understand.

Lastly, if somebody arrives to the software list from a search engine, the list should have a title that indicates that it is CURRENTLY available in Neurodesk.

Let me know which of the above suggestions you like, and I can work on them.</div>

**Comment by stebo85** [comment]
-> try to generate a table based on apps.json or cvmfs-logfile + integrate tools installed in main container

**Comment by aswinnarayanan** [comment]
Thanks to @iishiishii, application list now available at https://neurodesk.github.io/applications/

**Comment by civier** [comment]
Big applause @iishiishii !!!
This, together with the fact that we can now use VScode within containers, are the coolest features that came out of the hackathon by far.
BTW, are you still in Singapore? I vaguely remember you mentioning moving abroad.

**Comment by iishiishii** [comment]
Glad it improves the search results! 
@civier  Actually I plan to go to Brisbane this March so hopefully they won't shut the border again.

**Comment by stebo85** [comment]
Great work @iishiishii :) once we setup the CI to automatically build the list it's all done and dusted :) Opening the issue for now until the automation is completed.

**Comment by stebo85** [comment]
automation completed: list gets build in neurocommand and is downloaded in hugo before build
