### ISSUE TITLE
add more docker troubleshooting information

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk.github.io#55]
It is often one of these 4 solutions:

Close and open the terminal and retry.
Log out and login again, or restart the machine (current user environment doesnt fully know docker is running)
Add your user to the OS docker group (current user doesnt have permission to run docker)
docker.sock permissions need to be changed (needs some manual intervention to fix)
EDIT: Might add these to a troubleshooting section in the docs
EDIT: kels's fix: Open docker GUI and accept T&Cs. Check that the docker engine is running

To troubleshoot docker, we can try a simpler container first:
docker run hello-world

**Comment by aswinnarayanan** [comment]
Done 423ac6b1a3b7e15764c4b30a067b52fd276a45de
