### ISSUE TITLE
should we add an events page where we list past and future talks and hackathons about the project?

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk.github.io#6]

**Comment by air2310** [comment]
This is a great idea! Especially since any tutorial information/ slides from older talks quickly become outdated, people can look up an upcoming workshop or talk to learn.

**Comment by aswinnarayanan** [comment]
We can a news page using docsy's blog tempalte

**Comment by stebo85** [comment]
yes, that's a great idea - in the blog we could post about new features as
well?

**Comment by aswinnarayanan** [comment]
New/Blog page added https://neurodesk.github.io/blog/

**Comment by stebo85** [comment]
ok, great! I will fill this with future and past events later this week :)

**Comment by stebo85** [comment]
ok, done adding future and past events :) I had to hack it a bit to make future events show up, not sure if this is the only way of doing this? Good like it is?
