### ISSUE TITLE
Depreciate News/Blog post

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurodesk.github.io#68]
@stebo85, Should we remove/archive the news on the top panel in favour of switching to twitter.
The twitter link is now on the main menu.

**Comment by stebo85** [comment]
Yes, this would be wonderful :) It is currently a lot of work for me to maintain the news and twitter, but twitter gives us much more reach.

**Comment by stebo85** [comment]
I would even rename Twitter to News?

**Comment by aswinnarayanan** [comment]
Done ed69439b9328435bd7cfb5296b49d26407405b5f
