### ISSUE TITLE
can we make clearer how to contriubte a new workflow?

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk.github.io#74]
feedback from @mrikasper:
- not clear from the template how to duplicate this and start a new workflow and contriubte back via a pull request. @air2310 ideas how to describe this workflow well?

**Comment by air2310** [comment]
I'll ammend the template to include some more detailed step by step instructions on how to do this :)

**Comment by mrikasper** [comment]
I am currently going through the process for the Tutorials section. The template is great to familiarize people with MarkDown and its special dialect for hugo-docsy(?), but to actually create a new documentation entry, there are quite some extra steps involved, e.g.:
- forking the repo 
- how to edit new (`.md`) pages? Just in the browser? But I didn't find out how to create new folders (like "structural imaging" or "phase processing") online, only files. So do I have to do this offline?
- Is there a recommended offline editor/git tool (e.g., GitHub Desktop) to create the documentation files? How do I preview those then?

Would be great to have some more info or maybe pointers to other tutorials to get started.

**Comment by stebo85** [comment]
+ add description on how to preview the page in a fork

**Comment by air2310** [comment]
I've added a section detailing how to contribute a new workflow to the template. I actually didn't realised there was a way to preview the page from a fork though! I'll leave this issue open until I can chat to you (@stebo85) about this on Wednesday and get that final step documented :)
