### ISSUE TITLE
Fork of neurodesk.github.io not loading css

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurodesk.github.io#81]
@stebo85
> I added how to preview build the fork, but it's not yet quite working:
> https://stebo85.github.io/neurodesk.github.io/ - do you see what I am doing wrong?

**Comment by aswinnarayanan** [comment]
This is because the baseUrl below is set to https://neurodesk.github.io/. So the css and relative paths aren't loading properly

https://github.com/NeuroDesk/neurodesk.github.io/blob/4facc3cf2436b3eb68f53138fe2872c8ddb4772e/config.toml#L1

Might need to figure out a solution for this

**Comment by stebo85** [comment]
ideas:
- variable? github action to intercept and change base URL?

**Comment by aswinnarayanan** [comment]
Fixed. bcec4535d8ed097b39ee46e9059d8f10c312e66a

**Comment by stebo85** [comment]
Thank you :)
