### ISSUE TITLE
workflowtemplate - instructions re: images

### ISSUE THREAD

**Issue by kel-github** [NeuroDesk/neurodesk.github.io#92]
The section on inserting images doesn't contain any markdown syntax for inserting the image 
Rather it just shows the image itself directly after stating: To add screenshots to your tutorial, create a subfolder in neurodesk.github.io/static with the same link name as your tutorial. Add your screenshot to this folder, keeping in mind that you may want to adjust your screenshot to a reasonable size before uploading. You can then embed these images in your tutorial using the following convention:

**Comment by stebo85** [comment]
great find :) Thank you @kel-github!

Now looks like this:

![image](https://user-images.githubusercontent.com/4021595/149716917-2f16da09-324a-422a-a8c7-ba529f4ba2eb.png)
